### ISSUE TITLE
Is it possible for the library to support UDP protocol?

### ISSUE THREAD

**Issue by zhujunsan** [tray-labs/laravel-influxdb#15]
As TCP connections are slow and can throw exception, which is not good for using InfluxDB as a performance logger. On the contrary UDP is perfect for the job.

**Comment by greeneyz** [comment]
I have this query where I am getting an error of:
***************************
InfluxDB \ Exception
Query has failed
***************************

My query:
public function getLara()
    {

        // executing a query will yield a resultset object
        $result = InfluxDB::query('select * from candata where time > now() - 5m limit 10');

        // get the points from the resultset yields an array
        $points = $result->getPoints();

        return $points;
    }

**Comment by 1giba** [comment]
Follow the merge request to improves UDP to connect:
https://github.com/tray-labs/laravel-influxdb/pull/21
