### ISSUE TITLE
Query Failed

### ISSUE THREAD

**Issue by greeneyz** [tray-labs/laravel-influxdb#16]
I have this query where I am getting an error of:

InfluxDB \ Exception
Query has failed

My query:
public function getLara()
{

    // executing a query will yield a resultset object
    $result = InfluxDB::query('select * from candata where time > now() - 5m limit 10');

    // get the points from the resultset yields an array
    $points = $result->getPoints();

    return $points;
}

**Comment by 1giba** [comment]
Hi @greeneyz 

Please check your Influx configurations.

Regards @1giba
