### ISSUE TITLE
Updated installation instructions for 5.7 or 5.8?

### ISSUE THREAD

**Issue by fbc** [tray-labs/laravel-influxdb#17]
It would be really awesome to get updated instructions for 5.7 and 5.8 since the installation and quicker with the auto-discovery and all.

**Comment by xeno010** [comment]
see https://github.com/tray-labs/laravel-influxdb/issues/18#issuecomment-533774272

**Comment by tray-labs** [comment]
solved, added support version to auto discover and updated instructions
