### ISSUE TITLE
InfluxDB\Exception  Timed out

### ISSUE THREAD

**Issue by saeedulhassan23** [tray-labs/laravel-influxdb#29]
InfluxDB\Exception
Query has failed: cURL error 28: Failed to connect to ***.***.***.*** port 8806: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

How I can Fix it

**Comment by 1giba** [comment]
You must check your connection:

```bash
telnet localhost 8086
```
I'll close this issue, but if the problem occurs again you can reopen this issue or create a new one.
