### ISSUE TITLE
Support for Laravel 9

### ISSUE THREAD

**Issue by dcortez** [tray-labs/laravel-influxdb#32]
Laravel 9 has been released.

**Comment by dcortez** [comment]
Packagist is set to not "auto-update". Any chance you can push it over there too?

**Comment by 1giba** [comment]
@honjoya could you?

**Comment by honjoya** [comment]
Hi @1giba, i activated auto-update feature... thanks


<img width="822" alt="image" src="https://user-images.githubusercontent.com/688954/154805266-1afc05bf-da63-4abb-980d-7213fb8ac7de.png">
